#!/usr/bin/env bash

version=$(curl -sX GET "https://api.github.com/repos/mem0ai/mem0/releases" | jq --raw-output '[.[] | select(.tag_name | test("^v[0-9]+\\.[0-9]+\\.[0-9]+$"))][0].tag_name' | sed 's/^v//')
printf "%s" "${version}"
