#!/usr/bin/env bash

# Need a fix version https://cloudnative-pg.io/documentation/1.23/container_images/
repo="codesandbox/codesandbox-client"
version=$(curl -sX GET "https://api.github.com/repos/${repo}/releases/latest" | jq --raw-output '.tag_name' | sed 's/^v//')
printf "%s" "${version}"